### ISSUE TITLE
Unhandled Promise Rejection before tests are running

### ISSUE THREAD

**Issue by JacksonLei123** [reportportal/agent-js-playwright#104] opened 2023-06-09 21:25 UTC
Getting this error before any of the tests are run: 

**[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "AxiosError: Request failed with status code 400".] 
{code: 'ERR_UNHANDLED_REJECTION'
}**

Any ideas of what could be causing this issue?

**Comment by AmsterGet** [comment] 2023-06-12 10:10
Hello @JacksonLei123 !
Could you please provide your playwright and RP agent configs?

**Comment by JacksonLei123** [comment] 2023-06-14 16:09
Sure! Basically I have:

```
export const RPconfig = {
     token: TOKEN,
     endpoint: ENDPOINT,
     project: PROJECT,
     launch: LAUNCH_NAME
};
const config: PlaywrightTestConfig = { 
    projects: [{
         name: PROJECTNAME,
         testDir: TESTDIRECTORY,
         use: {
            browserName: 'chromium',
            proxy : {server: SERVERURL}
         }
    }],
   reporter: ['@reportportal/agent-js-playwright', RPconfig}]

}
```
I would run `npx playwright test --project=PROJECTNAME` then the console logs **Running x tests using y worker** and then that when the error gets shown

**Comment by AmsterGet** [comment] 2023-06-17 13:59
Do the following requests reach the RP server?
Could you run the tests with `debug: true` to collect more verbose output related to the requests the agent sends.

**Comment by JacksonLei123** [comment] 2023-06-19 02:56
It doesn't look like the requests reach the RP server since I don't see any tests being registered in the Report Portal UI. After running the tests with `debug: true`, I additionally get:


**Start launch with tempId TEMPID** 
```
{
    name: LAUNCH_NAME,
    startTime: 1687142600372,
    description: undefined,
    attributes: [
          {
             key: 'agent'
             value: '@reportportal/agent-js-playwright|5.1.0',
             system: true
          }
   ],
   rerun: undefined,
   rerunOf: undefined,
   mode: 'DEFAULT',
   id: undefined
}
```
followed by the original error

**Comment by AmsterGet** [comment] 2023-06-20 15:56
The logged request you provided looks fine.
Could you run our [example](https://github.com/reportportal/examples-js/tree/master/example-playwright) and make sure the behavior is still there?
I just want to exclude network-specific and RP instance errors to make sure the issue is on the agent side.

**Comment by JacksonLei123** [comment] 2023-06-20 16:33
Yup the error is still there when I run the example

**Comment by AmsterGet** [comment] 2023-06-21 09:20
So seems like the issue is not related to this agent, because the examples works fine.
What is your reportportal version?

**Comment by AmsterGet** [comment] 2023-08-06 13:39
Hello @JacksonLei123 !
Is the issue still relevant?
Could you please try to start the new launch by RP API request? 
You can use Swagger API spec from API page:

![image](https://github.com/reportportal/agent-js-playwright/assets/31861805/282b701e-ce7c-4fdc-995d-0bb871bcf3ff)

![image](https://github.com/reportportal/agent-js-playwright/assets/31861805/b430fdde-2ee0-402d-b1ad-7a6cf540e44e)

If I understand correctly, you inserted `LAUNCH_NAME` without quotes as a placeholder, but in fact you configured the launch name as a string.
I'm still assuming there's an issue with the RP API service as the request you shared looks valid and can't throw a 400 error.

**Comment by AmsterGet** [comment] 2024-01-03 18:02
Hello @JacksonLei123 !
Is your issue still relevant?

**Comment by AmsterGet** [comment] 2024-07-10 08:48
Hello @JacksonLei123 !
I'll close the issue for now, feel free to reopen it if needed.

**Closed by AmsterGet** 2024-07-10 08:48 UTC
Labels: Check: UI
