### ISSUE TITLE
Failing on Cannot read properties of undefined (reading 'testCount')

### ISSUE THREAD

**Issue by vinilvasani** [reportportal/agent-js-playwright#77] opened 2023-01-11 11:02 UTC
`"@playwright/test": "1.23.3"`
`"@reportportal/agent-js-playwright": "5.0.8"`

Getting the following error from reporter 
```
TypeError: Cannot read properties of undefined (reading 'testCount')
    at RPReporter.<anonymous> (/app/node_modules/@reportportal/agent-js-playwright/src/reporter.ts:487:40)
    at step (/app/node_modules/@reportportal/agent-js-playwright/build/reporter.js:60:23)
    at Object.next (/app/node_modules/@reportportal/agent-js-playwright/build/reporter.js:41:53)
    at fulfilled (/app/node_modules/@reportportal/agent-js-playwright/build/reporter.js:32:58) 
```

This is producing the error:
```
// if all children of the test parent have already finished, then finish all empty ancestors
    if (this.suites.get(fullParentName).testCount < 1) {
      this.finishSuites();
}
```

Would like to understand when would `fullParentName` not be present in the suites Map and if it can be accessed through optional chaining

**Comment by AmsterGet** [comment] 2023-02-24 13:13
Hello @vinilvasani !
As far as I remember, such a case can arise when the requested parent is already finished.
It would be very helpful if you could prepare a reproducible sample for this issue.

**Comment by AmsterGet** [comment] 2023-03-13 20:02
Hello @vinilvasani !
Could you please provide an example to help us reproduce the issue?
Thank you in advance!

**Comment by vinilvasani** [comment] 2023-03-14 07:49
Hey, @AmsterGet thank you for the response.
Will need some time to prepare a reproducible sample for this as this was an intermittent issue that I was facing.
Closing this, for now, will reopen the issues once I have the sample ready.

**Comment by sumit-gupta91** [comment] 2023-03-14 08:56
@AmsterGet @vinilvasani We are still facing this, I cannot share a reproducible issue as this is an internal project and since this does happens all the time, it is difficult for me to generate a scenario which reproduces this.

I still need to debug this because essentially entire suite gets cancelled after this error comes.

@AmsterGet Will it be possible for you to explain how I can debug this error on my side ? 

1. What does parent suite means
2. what are child suites
3. What happens if one of the test fails
4. What happens if response from API is not properly handled ?.

![Report portal agent playwright failure](https://user-images.githubusercontent.com/6623629/224947681-644bd488-a140-4257-8b72-b4a7af165575.jpg)

**Comment by sumit-gupta91** [comment] 2023-03-14 10:29
@AmsterGet There is another issue we are facing and I will be happy to pick both these issues up if I can help. 
Second issue - https://github.com/reportportal/agent-js-playwright/issues/86

**Comment by sumit-gupta91** [comment] 2023-03-14 10:45
@AmsterGet is there a way I can run agent-js-playwright in debug mode, which gives outputs like parent test suite, current test running and root suite ? from there I will be able to see patterns about which parent suite is always causing problems.

**Comment by AmsterGet** [comment] 2023-03-14 12:38
> @AmsterGet is there a way I can run agent-js-playwright in debug mode, which gives outputs like parent test suite, current test running and root suite ? from there I will be able to see patterns about which parent suite is always causing problems.

You can set the `debug: true` property in the config to see the debug logs from client-javascript.
No additional logging available from agent-js-playwright side.

**Comment by sumit-gupta91** [comment] 2023-03-16 06:43
@AmsterGet Hi, I ran report portal agent-js-playwright in debug mode to get more insights as to what test suite might be the culprit which could be causing this issue but the logs generated in debug mode are of no use. 

Attaching a sample here:
<img width="938" alt="Screenshot 2023-03-16 at 12 11 44 PM" src="https://user-images.githubusercontent.com/6623629/225536156-ee62c2d7-4a3b-414b-867a-7e39f918adb4.png">

**Comment by AmsterGet** [comment] 2023-03-16 08:55
Hello @sumit-gupta91 !
Seems like you are using not the last version of `client-javascript`, please reinstall the latest version of `agent-js-playwright` (it will use the latest version 5.0.8 of `client-javascript` with more verbose debug logs) and try again.

**Comment by AmsterGet** [comment] 2023-04-14 11:04
@sumit-gupta91  @vinilvasani @piti118
Hello guys!
Recently we've released the new version of the agent that should fix this issue.
Please try to run your tests with the latest version.
Looking forward for the feedback from you.

**Comment by sumit-gupta91** [comment] 2023-04-19 05:38
@AmsterGet Awesome. Let me upgrade and share results

**Comment by sumit-gupta91** [comment] 2023-05-03 05:43
@AmsterGet after upgrading to the latest version, we are no longer facing this issue. Thanks, for all the support.

**Comment by AmsterGet** [comment] 2023-05-21 14:06
So I'll close the issue.
Feel free to reopen if needed.

**Closed by AmsterGet** 2023-05-21 14:06 UTC
Labels: bug
